### ISSUE TITLE
Does not work on Windows due to cxxfilt

### ISSUE THREAD

**Issue by cHemingway** [metal-ci/test#3]
[serial/elfreader.py](https://github.com/metal-ci/test/blob/a33a6c169b451df664d9365ba6671e44d9a31fc8/metal/serial/elfreader.py#L9) includes cxxfilt which does not work on Windows, as it tries to use `__cxa_demangle()` from libc, which does not exist. This fails at runtime as libc cannot be opened by ctypes.
 I have opened an [issue](https://github.com/afq984/python-cxxfilt/issues/6), but don't really know how to address it, as its not clear what the _right_ behaviour is for that specific library on Windows.

Instead, it appears [python-itanium-demangler](https://github.com/whitequark/python-itanium_demangler) could work, as this decodes the [Itanium C++ API ](http://itanium-cxx-abi.github.io/cxx-abi/)which is still used by GCC/Clang, and [older versions](https://en.wikipedia.org/wiki/Name_mangling#How_different_compilers_mangle_the_same_functions) of IAR. It is in pure python so should work on any platform, and can return a string the same way. Looking at the tests, it seems the following should work:
```python
demangled = str(itanium_demangler.parse(mangled)
```

**Comment by klemens-morgenstern** [comment]
I just need a demangler. Can you create a PR to trigger the CI with the other demangling library?
